imports:
    - { resource: parameters.yml }
    - { resource: ini_parameters.yml }
    - { resource: security.yml }
    - { resource: logging.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
parameters:
    # based on the hardcoded value in
    # https://github.com/OpenConext/OpenConext-engineblock/blob/
    #   4102bffe58a9ecbce3c7c934e0aa8ece46efcf82/library/EngineBlock/Application/Bootstrapper.php#L242
    locale: nl

open_conext_engine_block:
    features:
        api.metadata_push:   "%feature_api_metadata_push%"
        api.consent_listing: "%feature_api_consent_listing%"
        api.metadata_api:    "%feature_api_metadata_api%"
        eb.encrypted_assertions: "%feature_eb_encrypted_assertions%"
        eb.encrypted_assertions_require_outer_signature: "%feature_eb_encrypted_assertions_require_outer_signature%"
        eb.run_all_manipulations_prior_to_consent: "%feature_run_all_manipulations_prior_to_consent%"

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['php']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: "%trusted_proxies%"
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

doctrine:
    dbal:
        default_connection: engineblock
        connections:
            engineblock:
#                schema_filter: ~^(?!group_|virtual_|service_provider_|saml_persistent_id|sso_provider_roles|log_logins|db_changelog|consent)~
                driver:   pdo_mysql         # This must be PDO until all database interaction runs through doctrine
                dbname:   "%database.dbname%"
                host:     "%database.host%"
                port:     "%database.port%"
                user:     "%database.user%"
                password: "%database.password%"
                charset:  UTF8
                # when true, queries are logged to a 'doctrine' monolog channel
                logging: '%kernel.debug%'
                profiling: '%kernel.debug%'
                server_version: 5.5
                mapping_types:
                    enum: string
        types:
            engineblock_entity_id: OpenConext\EngineBlockBundle\Doctrine\Type\EntityIdType
            engineblock_entity_type: OpenConext\EngineBlockBundle\Doctrine\Type\EntityTypeType
            engineblock_json_metadata: OpenConext\EngineBlockBundle\Doctrine\Type\JsonMetadataType
            engineblock_saml_entity_uuid: OpenConext\EngineBlockBundle\Doctrine\Type\SamlEntityUuidType
            engineblock_collab_person_id: OpenConext\EngineBlockBundle\Doctrine\Type\CollabPersonIdType
            engineblock_collab_person_uuid: OpenConext\EngineBlockBundle\Doctrine\Type\CollabPersonUuidType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        proxy_dir: '%kernel.cache_dir%/doctrine/orm/Proxies'
        entity_managers:
            engineblock:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                query_cache_driver:
                    type: apc
                metadata_cache_driver:
                    type: apc
                result_cache_driver:
                    type: apc
                connection: ~
                mappings:
                    # An array of mappings, which may be a bundle name or something else
                    Authentication:
                        mapping:   true
                        type:      annotation
                        dir:       "%kernel.root_dir%/../src/OpenConext/EngineBlockBundle/Authentication"
                        prefix:    OpenConext\EngineBlockBundle\Authentication
                        is_bundle: false
                    Metadata:
                        mapping:   true
                        type:      annotation
                        dir:       "%kernel.root_dir%/../src/OpenConext/EngineBlockBundle/Metadata"
                        prefix:    OpenConext\EngineBlockBundle\Metadata
                        is_bundle: false
                    EngineBlockMetadata:
                        mapping:   true
                        type:      annotation
                        dir:       "%kernel.root_dir%/../vendor/openconext/engineblock-metadata/src/Entity"
                        prefix:    OpenConext\Component\EngineBlockMetadata
                        is_bundle: false

doctrine_migrations:
    dir_name:   "%kernel.root_dir%/../database/DoctrineMigrations"
    namespace:  OpenConext\EngineBlock\Doctrine\Migrations
    table_name: migration_versions
    name:       OpenConext EngineBlock Migrations
