services:
    engineblock.minimum_execution_time_on_invalid_received_response:
        class: OpenConext\EngineBlockBundle\Value\ExecutionTime
        factory: [ OpenConext\EngineBlockBundle\Value\ExecutionTime, "of" ]
        arguments:
            - "%minimum_execution_time_on_invalid_received_response%"

    engineblock.request.request_id_generator:
        public: false
        class: OpenConext\EngineBlock\Request\UniqidGenerator

    engineblock.request.request_id:
        class: OpenConext\EngineBlock\Request\RequestId
        arguments:
            - "@engineblock.request.request_id_generator"

    engineblock.security.http_basic_entry_point:
        class: OpenConext\EngineBlockBundle\Security\Http\EntryPoint\JsonBasicAuthenticationEntryPoint
        arguments:
            - "engine-api.%domain%"

    engineblock.service.consent:
        class: OpenConext\EngineBlock\Service\ConsentService
        arguments:
            - "@engineblock.repository.consent"
            - "@engineblock.service.metadata"
            - "@engineblock.compat.logger"

    engineblock.service.metadata:
        class: OpenConext\EngineBlock\Service\MetadataService
        arguments:
            - "@engineblock.compat.repository.metadata"
            - "@engineblock.compat.logger"

    engineblock.authentication.user_directory:
        class: OpenConext\EngineBlockBundle\Authentication\Service\UserService
        arguments:
            - "@engineblock.repository.user"

    engineblock.features:
        class: OpenConext\EngineBlockBundle\Configuration\FeatureConfiguration
        arguments:
            - # replaced in the extension

    engineblock.pdp.pdp_client:
        class: OpenConext\EngineBlockBundle\Pdp\PdpClient
        arguments:
            - "@engineblock.pdp.http_client"
            - "%pdp.policy_decision_point_path%"

    engineblock.pdp.http_client:
        class: OpenConext\EngineBlock\Http\HttpClient
        arguments:
            - "@engineblock.pdp.guzzle_http_client"

    engineblock.pdp.guzzle_http_client:
        class: GuzzleHttp\Client
        arguments:
            - base_uri: "%pdp.host%"
              auth: ["%pdp.username%", "%pdp.password%", "Basic"]
              # Verify CAs for certificates for prod, but not for other environments
              # as we are working with self signed signatures
              verify: "@=service('kernel').getEnvironment() === 'prod'"

    engineblock.authentication.authentication_loop_guard:
        class: OpenConext\EngineBlockBundle\Authentication\AuthenticationLoopGuard
        arguments:
            - "%maximum_authentication_procedures_allowed%"
            - "%time_frame_for_authentication_loop_in_seconds%"

    engineblock.locale_provider:
        class: OpenConext\EngineBlockBundle\Localization\LocaleProvider
        arguments:
            - ['en', 'nl']
            - '%kernel.default_locale%'

    engineblock.locale.cookie_factory:
        class: OpenConext\EngineBlockBundle\Http\Cookies\CookieFactory
        arguments:
            - 'lang'
            - '%cookie.locale.domain%'
            - '%cookie.locale.expiry%'
            - '%cookie.locale.http_only%'
            - '%cookie.locale.secure%'

    engineblock.attribute_aggregation.client:
        class: OpenConext\EngineBlockBundle\AttributeAggregation\AttributeAggregationClient
        arguments:
            - "@engineblock.attribute_aggregation.http_client"
            - "%attribute_aggregation.base_url%"

    engineblock.attribute_aggregation.http_client:
        class: OpenConext\EngineBlock\Http\HttpClient
        arguments:
            - "@engineblock.attribute_aggregation.guzzle_http_client"

    engineblock.attribute_aggregation.guzzle_http_client:
        class: GuzzleHttp\Client
        arguments:
            - auth: ["%attribute_aggregation.username%", "%attribute_aggregation.password%", "Basic"]
